const mongoose = require('mongoose');

const itemSchema = mongoose.Schema({
    UTID: {type:String},
    recorder: {type:String},
    BBH: {type:String},
    C2: {type:String},
    C3A: {type:String},
    C4A: {type:String},
    C5A: {type:String},
    C6A: {type:String},
    C7A: {type:String},
    T1A: {type:String},
    T2A: {type:String},
    T3A: {type:String},
    T4A: {type:String},
    T5A: {type:String},
    T6A: {type:String},
    T7A: {type:String},
    T8A: {type:String},
    T9A: {type:String},
    T10A: {type:String},
    T11A: {type:String},
    T12A: {type:String},
    L1A: {type:String},
    L2A: {type:String},
    L3A: {type:String},
    L4A: {type:String},
    L5A: {type:String},
    XT: {type:String},
    S1: {type:String},
    ANK: {type:String},
    ANK_L: {type:String},
    ANK_R: {type:String},
    C3P: {type:String},
    C4P: {type:String},
    C5P: {type:String},
    C6P: {type:String},
    C7P: {type:String},
    T1P: {type:String},
    T2P: {type:String},
    T3P: {type:String},
    T4P: {type:String},
    T5P: {type:String},
    T6P: {type:String},
    T7P: {type:String},
    T8P: {type:String},
    T9P: {type:String},
    T10P: {type:String},
    T11P: {type:String},
    T12P: {type:String},
    L1P: {type:String},
    L2P: {type:String},
    L3P: {type:String},
    L4P: {type:String},
    L5P: {type:String},
    XT2: {type:String}
})

module.exports = mongoose.model('Fully-Metric', itemSchema);